
# ================== LOCAL DATABASE ==================
spring.datasource.url=jdbc:mysql://localhost:3306/new_customer_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================== PUBSUB (Local with key.json) ==================
spring.cloud.gcp.project-id=payments-dev-488506
spring.cloud.gcp.credentials.location=classpath:key.json