server.port=${PORT:8080}

spring.application.name=TRANSACTION-SERVICE

# ================= DATABASE =================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ================= SERVICES =================
account.service.url=${ACCOUNT_SERVICE_URL}
customer.service.url=${CUSTOMER_SERVICE_URL}

logging.level.root=INFO
logging.level.com.bank.transaction_service=DEBUG
spring.cloud.gcp.sql.enabled=false

spring.cloud.gcp.project-id=payments-dev-488506
#spring.cloud.gcp.credentials.location=file:/home/dml-aditi/keys/gcp-key.json

payment.pubsub.subscription=payment-events-sub
management.health.pubsub.enabled=false
