package com.bank.transaction_service.enums;

public enum ErrorCode {
    UNAUTHORIZED_ACCESS,
    INSUFFICIENT_BALANCE,
    TRANSACTION_NOT_FOUND,
    INVALID_TRANSACTION,
    LIMIT_EXCEEDED,
    ACCOUNT_NOT_FOUND,
    INVALID_BENEFICIARY,
    EXTERNAL_SERVICE_ERROR,
    BAD_REQUEST,
    INTERNAL_ERROR
}
